const SET_ACTIVED_CHANNEL = 'SET_ACTIVED_CHANNEL'
const SET_ACTIVED_SPACE = 'SET_ACTIVED_SPACE'
const SET_ACTIVED_PANEL = 'SET_ACTIVED_PANEL'
const SET_MASK = 'SET_MASK'
export default { SET_ACTIVED_CHANNEL, SET_ACTIVED_SPACE, SET_ACTIVED_PANEL, SET_MASK }