const SET_ACTIVED_CHANNEL = 'SET_ACTIVED_CHANNEL'
const SET_ACTIVED_SPACE = 'SET_ACTIVED_SPACE'
const SET_ACTIVED_PANEL = 'SET_ACTIVED_PANEL'
export default { SET_ACTIVED_CHANNEL, SET_ACTIVED_SPACE,SET_ACTIVED_PANEL }